- name: Init Playbook
  hosts: local
  connection: local
  become: true

  roles:
    - user
    - packages
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform
